services:
  catvault:
    build: .
    restart: unless-stopped
    container_name: catvault
    ports:
      - "5098:8080"
    volumes:
      - ./flag.txt:/flag.txt
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: "1"
      MARIADB_DATABASE: "catvault"
      MARIADB_USER: "meower"
      MARIADB_PASSWORD: "meowmeowmeow"